server:
  port: 8080

spring:
  application:
    name: aws-service
  datasource:
    url: jdbc:mysql://aws.cgj5ug4rlwwk.eu-central-1.rds.amazonaws.com:3306/deployment
    username: root
    password: root.1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl